### ISSUE TITLE
Create new target using xcproj cli

### ISSUE THREAD

**Issue by bartolkaruza** [0xced/xcproj#19]
I'm looking for a way to automate creating new targets for an existing project. Would this be possible with xcproj? I'm not sure what the 'all configurations' means in: "\* add-xcconfig <xcconfig_path>
     Add an xcconfig file to the project and base all configurations on it"

**Comment by 0xced** [comment]
> I'm looking for a way to automate creating new targets for an existing project. Would this be possible with xcproj?

It’s currently not possible, but I will look into it. The tricky part is how to specify which kind of target you want, e.g. an iOS app, a macOS CLI app, a unit test target etc.

> I'm not sure what the 'all configurations' means in: "\* add-xcconfig 
> Add an xcconfig file to the project and base all configurations on it"

Configurations are typically _Debug_ and _Release_. Here’s a screenshot that shows what happens after running `xcproj add-xcconfig Warnings.xcconfig` on Sandbox.xcodeproj.

<img width="740" alt="screen shot 2016-08-01 at 21 16 49" src="https://cloud.githubusercontent.com/assets/51363/17305958/ad60f872-582d-11e6-851b-943e4c99a9a1.png">

**Comment by bartolkaruza** [comment]
Ok, I had to keep going on this functionality for our project so I made it work with another library similar to xcproj (but for node) https://github.com/alunny/node-xcode

node-xcode has a bit more flexibility (and maintenance risk) by using a full .pbxproj grammar and writing changes directly to the pbxproj file, instead of using any of the API at IDEFoundation.h
