### ISSUE TITLE
XCode8 not work

### ISSUE THREAD

**Issue by njafei** [0xced/xcproj#20]
when I upgrade XCode to 8.1,it fail to change code sign.
this is log:

The IDEFoundation framework failed to load: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation): Library not loaded: @rpath/DVTAnalytics.framework/Versions/A/DVTAnalytics
  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation): Library not loaded: @rpath/DVTAnalytics.framework/Versions/A/DVTAnalytics
  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework, NSLocalizedDescription=The bundle “IDEFoundation” couldn’t be loaded because it is damaged or missing necessary resources.}

**Comment by 0xced** [comment]
I can not reproduce this problem on my end. Are you using the latest version of xcproj from the develop branch?

**Comment by njafei** [comment]
@0xced  I use the last release version 0.2,so i should use develop branch?

**Comment by 0xced** [comment]
Yes, please try with the develop branch.

**Comment by njafei** [comment]
ok,thx
